package main

import (
	"fmt"
	"log"
	"strings"

	"github.com/purpleclay/chomp"
)

type FileDiff struct {
	Path   string
	Chunks []DiffChunk
}

func (d FileDiff) String() string {
	var buf strings.Builder
	buf.WriteString(fmt.Sprintf("path: %s\n", d.Path))
	for _, chunk := range d.Chunks {
		buf.WriteString(chunk.String())
	}

	return buf.String()
}

type DiffChunk struct {
	Added   DiffChange
	Removed DiffChange
}

func (d DiffChunk) String() string {
	var buf strings.Builder
	buf.WriteString(d.Added.String())
	buf.WriteString(d.Removed.String())

	return buf.String()
}

// TODO: temporarily convert these into strings, and then look into a map function
type DiffChange struct {
	LineNo int
	Count  int
	Change string
}

func (d DiffChange) String() string {
	var buf strings.Builder
	buf.WriteString(fmt.Sprintf("line: %d count: %d\n", d.LineNo, d.Count))
	buf.WriteString(fmt.Sprintf("changed:\n%s", d.Change))

	return buf.String()
}

func Parse(in string) (FileDiff, error) {
	rem, path, err := diffPath()(in)
	if err != nil {
		return FileDiff{}, err
	}

	rem, _, err = chomp.Until("@@")(rem)
	if err != nil {
		return FileDiff{}, err
	}

	chunks, err := diffChunks(rem)
	if err != nil {
		return FileDiff{}, err
	}

	return FileDiff{
		Path:   path,
		Chunks: chunks,
	}, nil
}

func diffPath() chomp.Combinator[string] {
	return func(s string) (string, string, error) {
		// diff --git a/scan/scanner.go b/scan/scanner.go
		var rem string
		var err error

		if rem, _, err = chomp.Tag("diff --git ")(s); err != nil {
			return rem, "", err
		}

		var path string
		if rem, path, err = chomp.Until(" ")(rem); err != nil {
			return rem, "", err
		}
		path = path[strings.Index(path, "/")+1:]

		rem, _, err = chomp.Eol()(rem)
		return rem, path, err
	}
}

func diffChunks(in string) ([]DiffChunk, error) {
	_, chunks, err := chomp.Many(diffChunk())(in)
	if err != nil {
		return nil, err
	}
	fmt.Println(chunks)

	// TODO: convert chunks into []DiffChunk > need a map function
	return []DiffChunk{
		{
			Added:   DiffChange{},
			Removed: DiffChange{},
		},
	}, nil
}

func diffChunk() chomp.Combinator[[]string] {
	return func(s string) (string, []string, error) {
		/*
			@@ -25 +3,3 @@ package scan
			-import "bytes"
			+import (
			+       "bytes"
			+)
		*/
		var rem string
		var err error

		var changes []string
		rem, changes, err = chomp.Delimited(
			chomp.Tag("@@ "),
			chomp.SepPair(diffChunkHeaderChange("-"), chomp.Tag(" "), diffChunkHeaderChange("+")),
			chomp.Eol(),
		)(s)
		if err != nil {
			return rem, nil, err
		}

		// TODO: need to convert string values into int (chomp provides a conversion function) > must
		// TODO: constrain these by the values from the change header

		var removed []string
		rem, removed, err = chomp.ManyN(chomp.Prefixed(chomp.Eol(), chomp.Tag("-")), 0)(rem)

		var added []string
		rem, added, err = chomp.ManyN(chomp.Prefixed(chomp.Eol(), chomp.Tag("+")), 0)(rem)

		return rem, append(changes, strings.Join(removed, "\n"), strings.Join(added, "\n")), nil
	}
}

func diffChunkHeaderChange(prefix string) chomp.Combinator[[]string] {
	return func(s string) (string, []string, error) {
		var rem string
		var err error

		// TODO: this can be condensed

		rem, _, err = chomp.Tag(prefix)(s)
		if err != nil {
			return rem, nil, err
		}

		var line string
		rem, line, err = chomp.While(chomp.IsDigit)(rem)
		if err != nil {
			return rem, nil, err
		}

		rem, _, err = chomp.Peek(chomp.Tag(","))(rem)
		if err != nil {
			return rem, []string{line, "1"}, nil
		}

		var changed string
		rem, changed, err = chomp.Prefixed(chomp.While(chomp.IsDigit), chomp.Tag(","))(rem)
		if err != nil {
			return rem, nil, err
		}

		return rem, []string{line, changed}, nil
	}
}

func main() {
	// generated by: git diff -U0 -- scan/scanner.go
	diff := `diff --git a/scan/scanner.go b/scan/scanner.go
index fdf8e52..02d20e5 100644
--- a/scan/scanner.go
+++ b/scan/scanner.go
@@ -25 +3,3 @@ package scan
-import "bytes"
+import (
+       "bytes"
+)
@@ -57,0 +38,25 @@ func eat(prefix byte, data []byte) []byte {
+
+// DiffLines is a split function for a [bufio.Scanner] that splits a git diff output
+// into multiple blocks of text, each prefixed by the diff --git marker. Each block
+// of text will be stripped of any leading and trailing whitespace. If the git diff
+// marker isn't detected, the entire block of text is returned, with any leading and
+// trailing whitespace stripped
+func DiffLines() func(data []byte, atEOF bool) (advance int, token []byte, err error) {
+       prefix := []byte("\ndiff --git")
+
+       return func(data []byte, atEOF bool) (advance int, token []byte, err error) {
+               if atEOF && len(data) == 0 {
+                       return 0, nil, nil
+               }
+
+               if i := bytes.Index(data, prefix); i >= 0 {
+                       return i + 1, bytes.TrimSpace(data[:i]), nil
+               }
+
+               if atEOF {
+                       return len(data), bytes.TrimSpace(data), nil
+               }
+
+               return 0, nil, nil
+       }
+}`

	fileDiff, err := Parse(diff)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(fileDiff)
}
