name: release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  release:
    runs-on: ubuntu-24.04
    name: release
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: cachix/install-nix-action@ab739621df7a23f52766f9ccc97f38da6b7af14f # v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Release Note
        id: release_notes
        run: |
          echo "note<<EOF" >> $GITHUB_OUTPUT
          nix run github:purpleclay/release-note >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2.6.1
        with:
          body: ${{ steps.release_notes.outputs.note }}
          make_latest: true
